let place1 = document.querySelector(`#place1`);
let place2 = document.querySelector(`#place2`);
let place3 = document.querySelector(`#place3`);
let place4 = document.querySelector(`#place4`);
let place5 = document.querySelector(`#place5`);
let place6 = document.querySelector(`#place6`);
let place7 = document.querySelector(`#place7`);
let place8 = document.querySelector(`#place8`);
let place9 = document.querySelector(`#place9`);
let place10 = document.querySelector(`#place10`);
let place11 = document.querySelector(`#place11`);
let place12 = document.querySelector(`#place12`);
let place13 = document.querySelector(`#place13`);
let place14 = document.querySelector(`#place14`);
let place15 = document.querySelector(`#place15`);
let place16 = document.querySelector(`#place16`);
let place17 = document.querySelector(`#place17`);
let place18 = document.querySelector(`#place18`);
let place19 = document.querySelector(`#place19`);
let place20 = document.querySelector(`#place20`);
let place21 = document.querySelector(`#place21`);
let place22 = document.querySelector(`#place22`);
let place23 = document.querySelector(`#place23`);
let place24 = document.querySelector(`#place24`);
let place25 = document.querySelector(`#place25`);
let place26 = document.querySelector(`#place26`);
let place27 = document.querySelector(`#place27`);
let place28 = document.querySelector(`#place28`);
let place29 = document.querySelector(`#place29`);
let place30 = document.querySelector(`#place30`);
let price = document.querySelector(`#price`);
let butmain = document.querySelector(`#button-main`);
let hall = document.querySelector(`#hall`);
let foot = document.querySelector(`#foot`);
let pricing = document.querySelector(`#pricing`);
let order = document.querySelector(`#order`);
let main = document.querySelector(`#main`);
let topicNode = document.querySelector(`#topic`);
let bodyNode = document.querySelector(`#body`);
let hallNode = document.querySelector(`#hall`);
let pprice1Node = document.querySelector(`#p-price1`);
let pprice2Node = document.querySelector(`#p-price2`);
let pprice3Node = document.querySelector(`#p-price3`);
let pprice4Node = document.querySelector(`#p-price4`);
let pprice5Node = document.querySelector(`#p-price5`);
let pprice6Node = document.querySelector(`#p-price6`);
let pprice7Node = document.querySelector(`#p-price7`);
let pprice8Node = document.querySelector(`#p-price8`);
let butformNode = document.querySelector(`#but-form`);
let prNode = document.querySelector(`#pr`);
let poleNode = document.querySelector(`#pole`);
let numNode = document.querySelector(`#num`);



let num = 0;

place1.addEventListener(`click`, function(){
    if(place1.classList.contains(`active`) == false){
        num++
    }else{
        num--
    }
    price.innerHTML = 200 * num;
    place1.classList.toggle(`active`);
});

place2.addEventListener(`click`, function(){
    if(place2.classList.contains(`active`) == false){
        num++
    }else{
        num--
    }
    price.innerHTML = 200 * num;
    place2.classList.toggle(`active`)
});

place3.addEventListener(`click`, function(){
    if(place3.classList.contains(`active`) == false){
        num++
    }else{
        num--
    }
    price.innerHTML = 200 * num;
    place3.classList.toggle(`active`)
});

place4.addEventListener(`click`, function(){
    if(place4.classList.contains(`active`) == false){
        num++
    }else{
        num--
    }
    price.innerHTML = 200 * num;
    place4.classList.toggle(`active`)
});

place5.addEventListener(`click`, function(){
    if(place5.classList.contains(`active`) == false){
        num++
    }else{
        num--
    }
    price.innerHTML = 200 * num;
    place5.classList.toggle(`active`)
});

place7.addEventListener(`click`, function(){
    if(place7.classList.contains(`active`) == false){
        num++
    }else{
        num--
    }
    price.innerHTML = 200 * num;
    place7.classList.toggle(`active`)
});

place8.addEventListener(`click`, function(){
    if(place8.classList.contains(`active`) == false){
        num++
    }else{
        num--
    }
    price.innerHTML = 200 * num;
    place8.classList.toggle(`active`)
});

place9.addEventListener(`click`, function(){
    if(place9.classList.contains(`active`) == false){
        num++
    }else{
        num--
    }
    price.innerHTML = 200 * num;
    place9.classList.toggle(`active`)
});

place10.addEventListener(`click`, function(){
    if(place10.classList.contains(`active`) == false){
        num++
    }else{
        num--
    }
    price.innerHTML = 200 * num;
    place10.classList.toggle(`active`)
});

place12.addEventListener(`click`, function(){
    if(place12.classList.contains(`active`) == false){
        num++
    }else{
        num--
    }
    price.innerHTML = 200 * num;
    place12.classList.toggle(`active`)
});


place13.addEventListener(`click`, function(){
    if(place13.classList.contains(`active`) == false){
        num++
    }else{
        num--
    }
    price.innerHTML = 200 * num;
    place13.classList.toggle(`active`)
});


place14.addEventListener(`click`, function(){
    if(place14.classList.contains(`active`) == false){
        num++
    }else{
        num--
    }
    price.innerHTML = 200 * num;
    place14.classList.toggle(`active`)
});

place15.addEventListener(`click`, function(){
    if(place15.classList.contains(`active`) == false){
        num++
    }else{
        num--
    }
    price.innerHTML = 200 * num;
    place15.classList.toggle(`active`)
});

place16.addEventListener(`click`, function(){
    if(place16.classList.contains(`active`) == false){
        num++
    }else{
        num--
    }
    price.innerHTML = 200 * num;
    place16.classList.toggle(`active`)
});

place18.addEventListener(`click`, function(){
    if(place18.classList.contains(`active`) == false){
        num++
    }else{
        num--
    }
    price.innerHTML = 200 * num;
    place18.classList.toggle(`active`)
});

place19.addEventListener(`click`, function(){
    if(place19.classList.contains(`active`) == false){
        num++
    }else{
        num--
    }
    price.innerHTML = 200 * num;
    place19.classList.toggle(`active`)
});

place20.addEventListener(`click`, function(){
    if(place20.classList.contains(`active`) == false){
        num++
    }else{
        num--
    }
    price.innerHTML = 200 * num;
    place20.classList.toggle(`active`)
});

place21.addEventListener(`click`, function(){
    if(place21.classList.contains(`active`) == false){
        num++
    }else{
        num--
    }
    price.innerHTML = 200 * num;
    place21.classList.toggle(`active`)
});
place22.addEventListener(`click`, function(){
    if(place22.classList.contains(`active`) == false){
        num++
    }else{
        num--
    }
    price.innerHTML = 200 * num;
    place22.classList.toggle(`active`)
});

place24.addEventListener(`click`, function(){
    if(place24.classList.contains(`active`) == false){
        num++
    }else{
        num--
    }
    price.innerHTML = 200 * num;
    place24.classList.toggle(`active`)
});

place25.addEventListener(`click`, function(){
    if(place25.classList.contains(`active`) == false){
        num++
    }else{
        num--
    }
    price.innerHTML = 200 * num;
    place25.classList.toggle(`active`)
});

place26.addEventListener(`click`, function(){
    if(place26.classList.contains(`active`) == false){
        num++
    }else{
        num--
    }
    price.innerHTML = 200 * num;
    place26.classList.toggle(`active`)
});

place28.addEventListener(`click`, function(){
    if(place28.classList.contains(`active`) == false){
        num++
    }else{
        num--
    }
    price.innerHTML = 200 * num;
    place28.classList.toggle(`active`)
});

place29.addEventListener(`click`, function(){
    if(place29.classList.contains(`active`) == false){
        num++
    }else{
        num--
    }
    price.innerHTML = 200 * num;
    place29.classList.toggle(`active`)
});

place30.addEventListener(`click`, function(){
    if(place30.classList.contains(`active`) == false){
        num++
    }else{
        num--
    }
    price.innerHTML = 200 * num;
    place30.classList.toggle(`active`);
});

let price000 = 0

butmain.addEventListener(`click`,function(){
    price000 = price.innerHTML
    hall.classList.add(`d-none`);
    foot.classList.add(`d-none`);
    pricing.classList.add(`d-none`);
    order.classList.add(`d-flex`);
    prNode.innerHTML = price000
});

let numm = numNode.value;

butformNode.addEventListener(`click`, function(){
    poleNode.innerHTML = `оплата совершена`;
});

topicNode.addEventListener(`click`, function(){
    bodyNode.classList.toggle(`night-topic`);
    hallNode.classList.toggle(`hall-night`);
    pprice1Node.classList.toggle(`p-night`);
    pprice2Node.classList.toggle(`p-night`);
    pprice3Node.classList.toggle(`p-night`);
    pprice4Node.classList.toggle(`p-night`);
    pprice5Node.classList.toggle(`p-night`);
    pprice6Node.classList.toggle(`p-night`);
    pprice7Node.classList.toggle(`p-night`);
    pprice8Node.classList.toggle(`p-night`);
    butmain.classList.toggle(`p-night`);
    butformNode.classList.toggle(`p-night`);
});